const express = require("express");
const apiRouter = express.Router();
const healthRouter = require("./health");
const usersRouter = require("./users");
const routinesRouter = require("./routines");
const activitiesRouter = require("./activities");
const routineActivitiesRouter = require("./routine_activities");
apiRouter.use("/health", healthRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/routines", routinesRouter);
apiRouter.use("/activities", activitiesRouter);
apiRouter.use("/routine_activities", routineActivitiesRouter);
module.exports = apiRouter;
